# These are supported funding model platforms

github: # https://github.com/buckinbuds/buckinbuds.io
patreon: # 
open_collective: # 
ko_fi: # 
tidelift: # 
community_bridge: # https://funding.communitybridge.org/projects/6a4ce9f3-2052-4bc9-9e0e-ab48f1f9c390
liberapay: # 
issuehunt: # 
otechie: # e
custom: # 
